### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by matthewstathis1** [psonnera/minimed-connect-to-nightscout-wrapper#2]
When running node run.js I get a request failed with status code 404 (see image). Any idea what might be causing this?
![5F510533-98EB-49DD-A8D9-525F80650D3D](https://user-images.githubusercontent.com/45523053/112743134-a7388c00-8f62-11eb-9e8e-23b556f023c5.jpeg)

**Comment by yacenty** [comment]
same on my installation

**Comment by Robinbloodsugar** [comment]
mine as well here is the log::

pi@mmconnect:~/minimed-connect-to-nightscout-wrapper $ node run.js
Error: Request failed with status code 404
stack: Error: Request failed with status code 404
    at createError (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/settle.js:17:12)
    at /home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:79:25
    at new Promise (<anonymous>)
    at responseInterceptor (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:78:9)
    at instance.interceptors.response.use.res (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/index.js:130:67)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Error: Request failed with status code 404
stack: Error: Request failed with status code 404
    at createError (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/settle.js:17:12)
    at /home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:79:25
    at new Promise (<anonymous>)
    at responseInterceptor (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:78:9)
    at instance.interceptors.response.use.res (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/index.js:130:67)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Request failed with status code 404
stack: Error: Request failed with status code 404
    at createError (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/settle.js:17:12)
    at /home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:79:25
    at new Promise (<anonymous>)
    at responseInterceptor (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:78:9)
    at instance.interceptors.response.use.res (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/index.js:130:67)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Request failed with status code 404
stack: Error: Request failed with status code 404
    at createError (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/settle.js:17:12)
    at /home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:79:25
    at new Promise (<anonymous>)
    at responseInterceptor (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:78:9)
    at instance.interceptors.response.use.res (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/index.js:130:67)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Request failed with status code 404
stack: Error: Request failed with status code 404
    at createError (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/settle.js:17:12)
    at /home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:79:25
    at new Promise (<anonymous>)
    at responseInterceptor (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:78:9)
    at instance.interceptors.response.use.res (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/index.js:130:67)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Request failed with status code 404
stack: Error: Request failed with status code 404
    at createError (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/settle.js:17:12)
    at /home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:79:25
    at new Promise (<anonymous>)
    at responseInterceptor (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:78:9)
    at instance.interceptors.response.use.res (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/index.js:130:67)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Request failed with status code 404
stack: Error: Request failed with status code 404
    at createError (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/settle.js:17:12)
    at /home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:79:25
    at new Promise (<anonymous>)
    at responseInterceptor (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:78:9)
    at instance.interceptors.response.use.res (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/index.js:130:67)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by matthewstathis1** [comment]
are you using a US or EU Carelink account? at first I was trying to use my usual US account and I was getting errors like that and then I switch to an EU account (and an EU login on the app on my phone) and that got me past those errors, now I just get a stale data error instead

**Comment by steinauf85** [comment]
same error for me as well. using US account.

2 factor is enabled on the account. perhaps that has something to do with it?

**Comment by steinauf85** [comment]
Seems that the US server is actively blocking connections as 404 errors happen regardless of credentials. The only way I was able to get data into Nightscout was to use an Android device with the [xDripCareLinkFollower](https://github.com/benceszasz/xDripCareLinkFollower) app installed from the APK at that link.

So, somehow that app is able to log in, but this one isn't. I'm wondering if it's the method that it uses to login, or if CareLink only allows access to certain device types? If the former, I wonder if the code could be implemented within this app. It is separated out into its own repository, https://github.com/benceszasz/CareLinkJavaClient.

Unfortunately I'm far too inexperienced to make this work, but I do think it would be great to have this work on my Pi if someone else is able to take a crack at it.

**Comment by MJS0007** [comment]
I have the same error myself, did you manage to find a fix?

**Comment by steinauf85** [comment]
No. Don’t think it’s functional at all. I use xdrip on an android device
instead
